const students = [
  {
    rollNo: "5221421001",
    name: "GODAVARTHY SRI RANGA PADMAVATHI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "MOOCS",
    attendancePercentage: "69.67%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421002",
    name: "DEKKATHA RESHMA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "61.48%",
    cgpa: "8.25",
  },
  {
    rollNo: "5221421003",
    name: "PULAPA DHANISHA NAGA SAI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "74.59%",
    cgpa: "7.98",
  },
  {
    rollNo: "5221421004",
    name: "GURUGUBELLI MANISHA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "84.43%",
    cgpa: "7.65",
  },
  {
    rollNo: "5221421005",
    name: "PUDI CHANDRIKA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "VLSI, ELEC62, ELEOP61",
    attendancePercentage: "58.20%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421006",
    name: "RACHAKONDA NAGA TEJASVI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "69.67%",
    cgpa: "8.40",
  },
  {
    rollNo: "5221421007",
    name: "AGRAHARAPU VIJAYANAND",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "VLSI",
    attendancePercentage: "72.95%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421008",
    name: "ANNAM PRABASH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP, MWE, VLSI, ELEC62, ELEOP61",
    attendancePercentage: "69.67%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421009",
    name: "ARASAVILLI KOUSALYA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "72.95%",
    cgpa: "8.98",
  },
  {
    rollNo: "5221421010",
    name: "ASHISH KUMAR SHA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "MOOCS",
    attendancePercentage: "48.36%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421011",
    name: "ATI VENKATA SUDHINDRA KUMAR",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "80.33%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421012",
    name: "BADIGANTI CHARMINI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "80.33%",
    cgpa: "8.34",
  },
  {
    rollNo: "5221421013",
    name: "BASAVA HARISH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP, ELEC62, ELEOP61, DSP LAB",
    attendancePercentage: "61.48%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421014",
    name: "BAVIRISETTI KUSUMALATHA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "64.75%",
    cgpa: "9.11",
  },
  {
    rollNo: "5221421015",
    name: "BEHARA JAYARAM",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP LAB",
    attendancePercentage: "73.77%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421016",
    name: "BENDALAM SUPRIYA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "65.57%",
    cgpa: "9.22",
  },
  {
    rollNo: "5221421017",
    name: "BOGAVILLI KRISH KANJ",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP LAB",
    attendancePercentage: "60.66%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421018",
    name: "BOLLI HARI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "60.66%",
    cgpa: "7.14",
  },
  {
    rollNo: "5221421019",
    name: "BUDDHA PRANEETH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "ELEC62",
    attendancePercentage: "77.05%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421020",
    name: "CHANDAKA HEMACHANDRUNAIDU",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "ELEC62",
    attendancePercentage: "66.39%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421021",
    name: "CHENAGala MOHIT YADAV",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "ELEC62, ELEOP61",
    attendancePercentage: "60.66%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421022",
    name: "CHIGILIPALLI DHILLESWARA RAO",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP LAB",
    attendancePercentage: "97.54%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421023",
    name: "CHIKKALA PURNA SATHVIK",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "ELEC62, ELEOP61",
    attendancePercentage: "83.61%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421024",
    name: "DAMMU SAI UMA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "86.89%",
    cgpa: "8.02",
  },
  {
    rollNo: "5221421025",
    name: "DAMMU SURYA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "68.85%",
    cgpa: "6.56",
  },
  {
    rollNo: "5221421026",
    name: "DODDA SIVA MANI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "77.87%",
    cgpa: "7.19",
  },
  {
    rollNo: "5221421028",
    name: "DUPPALA SRIPURVA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "81.15%",
    cgpa: "8.83",
  },
  {
    rollNo: "5221421029",
    name: "GALI AKSHAY",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "78.69%",
    cgpa: "7.41",
  },
  {
    rollNo: "5221421031",
    name: "GUNDA GOWRESWARI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "82.79%",
    cgpa: "7.90",
  },
  {
    rollNo: "5221421032",
    name: "GUNTLA RAMYA SRI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "ELEOP61",
    attendancePercentage: "41.80%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421033",
    name: "GURI KOWSHIK",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "93.44%",
    cgpa: "8.03",
  },
  {
    rollNo: "5221421034",
    name: "HARSHITH MOULI MUTHY",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "72.95%",
    cgpa: "8.17",
  },
  {
    rollNo: "5221421035",
    name: "HYNDHAVIS S PRASANNA VINNAKOTA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "76.23%",
    cgpa: "9.06",
  },
  {
    rollNo: "5221421036",
    name: "IMIDISETTY SURESH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "68.03%",
    cgpa: "8.13",
  },
  {
    rollNo: "5221421037",
    name: "J VENKATA SURYA VEERA CHINMAYA ALOK NADH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "66.39%",
    cgpa: "6.90",
  },
  {
    rollNo: "5221421038",
    name: "JALDU HARSHITHA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "83.61%",
    cgpa: "8.55",
  },
  {
    rollNo: "5221421039",
    name: "KADUPU KUMARA ΜΑΝΙΚΑΝΤA UMA MAHESH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "81.97%",
    cgpa: "6.99",
  },
  {
    rollNo: "5221421040",
    name: "KASIMKOTA HARSHITHA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "64.75%",
    cgpa: "7.36",
  },
  {
    rollNo: "5221421041",
    name: "KILARI GOPINATH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "68.85%",
    cgpa: "7.21",
  },
  {
    rollNo: "5221421042",
    name: "KINJANGI BILVA GOPAL",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "64.75%",
    cgpa: "7.21",
  },
  {
    rollNo: "5221421043",
    name: "KOLLI PURUSHOTHAM REDDY",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "47.54%",
    cgpa: "6.90",
  },
  {
    rollNo: "5221421044",
    name: "KOMMU SARATH KUMAR",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "70.49%",
    cgpa: "6.57",
  },
  {
    rollNo: "5221421045",
    name: "KONDA PAVANI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "100.00%",
    cgpa: "8.81",
  },
  {
    rollNo: "5221421046",
    name: "KOPPUROTHU TARUN VIKRAM",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "48.36%",
    cgpa: "7.08",
  },
  {
    rollNo: "5221421047",
    name: "KORADA THANAY",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "74.59%",
    cgpa: "7.30",
  },
  {
    rollNo: "5221421048",
    name: "KORRAYI GOUTHAM",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "68.03%",
    cgpa: "7.86",
  },
  {
    rollNo: "5221421050",
    name: "LANKALAPALLI BHUVAN SAI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "70.49%",
    cgpa: "6.61",
  },
  {
    rollNo: "5221421051",
    name: "LENKA KUSUMA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "86.89%",
    cgpa: "8.47",
  },
  {
    rollNo: "5221421052",
    name: "LOKAREDDY SAI SURYA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "50.00%",
    cgpa: "7.06",
  },
  {
    rollNo: "5221421053",
    name: "MADHU SUDHAN YADAV",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP",
    attendancePercentage: "71.31%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421054",
    name: "МАЈЛ ЈАHANAVI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "57.38%",
    cgpa: "7.28",
  },
  {
    rollNo: "5221421055",
    name: "MALLA DHARMA TEJA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "81.97%",
    cgpa: "7.04",
  },
  {
    rollNo: "5221421056",
    name: "MAMIDI SANKET",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "48.36%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421057",
    name: "MANCHIKALAPUDI PRASANTH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP, MWE, VLSI, ELEOP61, DSP LAB",
    attendancePercentage: "75.41%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421058",
    name: "MANTHRI POOJITHA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "65.57%",
    cgpa: "8.72",
  },
  {
    rollNo: "5221421059",
    name: "MATTA SRINU",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "66.39%",
    cgpa: "6.69",
  },
  {
    rollNo: "5221421060",
    name: "MEESALA SAI RAMESH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "MWE",
    attendancePercentage: "52.46%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421061",
    name: "MOHAMMAD AMEENA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "72.13%",
    cgpa: "8.02",
  },
  {
    rollNo: "5221421062",
    name: "N NANDA KALYANI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "80.33%",
    cgpa: "7.68",
  },
  {
    rollNo: "5221421063",
    name: "NAGOTHI SANYASIRAO",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "74.59%",
    cgpa: "6.89",
  },
  {
    rollNo: "5221421064",
    name: "ΝΑΚΚΑ ΜΑΝΙΚΑΝΤΑ",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "51.64%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421136",
    name: "SABBISETTY HEMANTH KUMAR",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "ELEOP61, MOOCS",
    attendancePercentage: "45.08%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421137",
    name: "SRIPARNA SARKAR",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "60.66%",
    cgpa: "7.59",
  },
  {
    rollNo: "5221421138",
    name: "SUVVADA PREETHAM",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP, ELEC62",
    attendancePercentage: "40.98%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421139",
    name: "TAKKELLAPATI SAI ADITYA TEJA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "81.97%",
    cgpa: "7.19",
  },
  {
    rollNo: "5221421140",
    name: "TATAKULA SRI DATTA ΜΑΝΙΚΑΝTA SRIJAN",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "72.95%",
    cgpa: "8.90",
  },
  {
    rollNo: "5221421141",
    name: "TEKETI HARSHA VARDHAN",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "VLSI, ELEOP61, MOOCS",
    attendancePercentage: "49.18%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421142",
    name: "TERUKUTI TULASI RAM",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "83.61%",
    cgpa: "6.91",
  },
  {
    rollNo: "5221421143",
    name: "VANDRANGI SUPRIYA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP, DSP LAB, MIC EN LAB, PCS",
    attendancePercentage: "9.84%",
    cgpa: "0.00",
  },
  {
    "rollNo": "5231421001",
    "name": "ABDUL ARIF",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "AEC",
    "cgpa": "0",
    "attendancePercentage": "51.85%"
  },
  {
    "rollNo": "5231421002",
    "name": "ALLU RAGA TANMAI SHANMUKA CHAITANYA",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "None",
    "cgpa": "7.82",
    "attendancePercentage": "46.67%"
  },
  {
    "rollNo": "5231421003",
    "name": "ALLURI HARSHAVEER",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "None",
    "cgpa": "8.39",
    "attendancePercentage": "74.07%"
  },
  {
    "rollNo": "5231421004",
    "name": "ALLUVADA NAGA PRABHA PATNAIK",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "None",
    "cgpa": "8.21",
    "attendancePercentage": "88.89%"
  },
  {
    "rollNo": "5231421005",
    "name": "AMBATI GEETHA DHANA SREE",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "None",
    "cgpa": "7.64",
    "attendancePercentage": "65.19%"
  },
  {
    "rollNo": "5231421006",
    "name": "ANNAMREDDY SIVA KUMAR",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "None",
    "cgpa": "9.02",
    "attendancePercentage": "70.37%"
  },
  {
    "rollNo": "5231421007",
    "name": "APPIKONDA VAMSI BABU",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "None",
    "cgpa": "7.02",
    "attendancePercentage": "48.15%"
  },
  {
    "rollNo": "5231421008",
    "name": "BADDA GEETHIKA",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "None",
    "cgpa": "9.21",
    "attendancePercentage": "91.85%"
  },
  {
    "rollNo": "5231421009",
    "name": "BANDARU MADHULIKA",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "None",
    "cgpa": "8.96",
    "attendancePercentage": "79.26%"
  },
  {
    "rollNo": "5231421010",
    "name": "BANDI PREETAM",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "S&S, SSS LAB",
    "cgpa": "0",
    "attendancePercentage": "48.89%"
  },
  {
    "rollNo": "5231421012",
    "name": "BELLANA KUMAR NAIDU",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "None",
    "cgpa": "7.79",
    "attendancePercentage": "71.11%"
  },
  {
    "rollNo": "5231421029",
    "name": "GOLAGANA PAVAN KUMAR",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "Engg. M-3 ECE, AEC, PDC, S&S, PE&UHV, AEC LAB, SSS LAB",
    "cgpa": "0",
    "attendancePercentage": "40.00%"
  },
  {
    "rollNo": "5231421032",
    "name": "GUMMALA SIDDU",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "Engg. M-3 ECE, AEC, PDC, S&S, PE&UHV, SSS LAB",
    "cgpa": "0",
    "attendancePercentage": "51.11%"
  },
  {
    "rollNo": "5231421052",
    "name": "KOTHAKOTA SNEHITH",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "Engg. M-3 ECE, AEC, PDC, S&S, AEC LAB, SSS LAB",
    "cgpa": "0",
    "attendancePercentage": "40.74%"
  },
  {
    "rollNo": "5231421139",
    "name": "PUKKALLA ROHIT",
    "year": "3rd",
    "stream": "ECE B.Tech",
    "backlogs": "Engg. M-3 ECE",
    "cgpa": "0",
    "attendancePercentage": "58.52%"
  },
  {
    rollNo: "5231421065",
    name: "MUVVALA RAM SAI VARA PREETHAM",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "74.68%",
    cgpa: "8.61",
  },
  {
    rollNo: "5231421066",
    name: "MYLIPALLI SIVA SHANKAR",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "AEC, PDC, PE&UHV, SSS LAB",
    attendancePercentage: "46.84%",
    cgpa: "0",
  },
  {
    rollNo: "5231421067",
    name: "NADIMPILLI SAIRAM VARMA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "87.82%",
    cgpa: "0",
  },
  {
    rollNo: "5231421068",
    name: "NALLAJARLA GVN SATYA VIJAY",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "AEC, PDC, PE&UHV",
    attendancePercentage: "71.79%",
    cgpa: "0",
  },
  {
    rollNo: "5231421069",
    name: "NANDIKA SATYA CHAITANYA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "56.33%",
    cgpa: "0",
  },
  {
    rollNo: "5231421070",
    name: "NAVEEN KUMAR G",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "E.M-III, PDC, S&S",
    attendancePercentage: "69.87%",
    cgpa: "0",
  },
  {
    rollNo: "5231421071",
    name: "NEMALA PRAVALLIKA LAKSHMI",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "84.81%",
    cgpa: "9.06",
  },
  {
    rollNo: "5231421072",
    name: "PASI BHANU KISHORE",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "E.M-III, AEC, PDC, S&S, PE&UHV, AEC LAB, DDV LAB, SSS LAB, PYTHON LAB",
    attendancePercentage: "65.19%",
    cgpa: "0",
  },
  {
    rollNo: "5231421073",
    name: "PEDAGADIG SKD SUVARNA ANUPRIYA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "74.68%",
    cgpa: "7.67",
  },
  {
    rollNo: "5231421074",
    name: "PEDDINTI VINESH",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "74.68%",
    cgpa: "7.64",
  },
  {
    rollNo: "5231421075",
    name: "PEDIREDLA JAHNAVI",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "72.78%",
    cgpa: "0",
  },
  {
    rollNo: "5231421076",
    name: "PEYYALA SUDHAKAR",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "AEC, PDC, S&S, PE&UHV, DDV LAB, SSS LAB",
    attendancePercentage: "62.18%",
    cgpa: "0",
  },
  {
    rollNo: "5231421077",
    name: "PILAKA LAXMI NARASIMHA REDDY",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PE&UHV",
    attendancePercentage: "71.15%",
    cgpa: "0",
  },
  {
    rollNo: "5231421078",
    name: "POLAMARASETTY AKSHAYA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "70.25%",
    cgpa: "0",
  },
  {
    rollNo: "5231421079",
    name: "POLAVARAPU V G VARA PRASAD",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "60.76%",
    cgpa: "0",
  },
  {
    rollNo: "5231421080",
    name: "PONNAPUVVU YERNI DURGA VIGNESH",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "E.M-III, PDC, DDV LAB, SSS LAB",
    attendancePercentage: "61.39%",
    cgpa: "0",
  },
  {
    rollNo: "5231421081",
    name: "POSINA PRAVALIKA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "78.48%",
    cgpa: "0",
  },
  {
    rollNo: "5231421082",
    name: "PYLA ASWINI",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "81.65%",
    cgpa: "8.91",
  },
  {
    rollNo: "5231421083",
    name: "RACHAMALLA DINESH BHUSHAN",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "68.59%",
    cgpa: "6.37",
  },
  {
    rollNo: "5231421084",
    name: "RAMADHENU VENKATA SATYA SAI MOHIT VAMSI",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "72.78%",
    cgpa: "7.37",
  },
  {
    rollNo: "5231421086",
    name: "RAVURI SATYA PHANI KRISHNA MURTHY",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "79.75%",
    cgpa: "0",
  },
  {
    rollNo: "5231421088",
    name: "REDDI KOWSALYA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "69.62%",
    cgpa: "8.12",
  },
  {
    rollNo: "5231421089",
    name: "ROKKAM BHARADWAJ",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "79.11%",
    cgpa: "8.53",
  },
  {
    rollNo: "5231421090",
    name: "SAGI SREE SASHANK VARMA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "72.44%",
    cgpa: "0",
  },
  {
    rollNo: "5231421091",
    name: "SANAPALA CHIDVILAS",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "69.62%",
    cgpa: "0",
  },
  {
    rollNo: "5231421092",
    name: "SILARAPU GAYATHRI GEETHIKA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "72.15%",
    cgpa: "0",
  },
  {
    rollNo: "5231421094",
    name: "SRIMATH TIRUMALA PURIGALLA R TEJASWINI",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "85.44%",
    cgpa: "8.91",
  },
  {
    rollNo: "5231421095",
    name: "SUNKARA RAMALAXMANA RAVI GANESH",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "E.M-III, PDC",
    attendancePercentage: "55.70%",
    cgpa: "0",
  },
  {
    rollNo: "5231421096",
    name: "SURADA UDAY RAAMESH LAKSHMI RADHA KRISHNA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC, PE&UHV",
    attendancePercentage: "33.54%",
    cgpa: "0",
  },
  {
    rollNo: "5231421097",
    name: "SURISETTY PUJITHA B VS GOWRI",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "78.48%",
    cgpa: "8.24",
  },
  {
    rollNo: "5231421098",
    name: "TAMMINAINA LIKHITHA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "87.18%",
    cgpa: "7.84",
  },
  {
    rollNo: "5231421099",
    name: "TANANKI SAI JAGADEESH",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "64.10%",
    cgpa: "0",
  },
  {
    rollNo: "5231421100",
    name: "THALARI ABHISHEK",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC, PE&UHV",
    attendancePercentage: "77.56%",
    cgpa: "0",
  },
  {
    rollNo: "5231421101",
    name: "UDDANGI KISHORE KUMAR",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "85.26%",
    cgpa: "8.44",
  },
  {
    rollNo: "5231421102",
    name: "UMMIDI KESAVA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "E.M-III, PDC",
    attendancePercentage: "54.43%",
    cgpa: "0",
  },
  {
    rollNo: "5231421103",
    name: "VADANA SAI PAVAN",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "E.M-III",
    attendancePercentage: "49.37%",
    cgpa: "0",
  },
  {
    rollNo: "5231421104",
    name: "VADICHARLA AKANKSHA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "70.97%",
    cgpa: "8.49",
  },
  {
    rollNo: "5231421105",
    name: "VANKAYALA GURUSRIRAMA PAVAN",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "60.65%",
    cgpa: "7.19",
  },
  {
    rollNo: "5231421106",
    name: "VANTRAPATI SASMITHA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "71.61%",
    cgpa: "9.03",
  },
  {
    rollNo: "5231421107",
    name: "VELPURI MURALI MANOHAR",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "53.55%",
    cgpa: "6.93",
  },
  {
    rollNo: "5231421108",
    name: "WALTAIRE YASHWANTH",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "71.61%",
    cgpa: "6.64",
  },
  {
    rollNo: "5231421109",
    name: "YELURU HARSHITHA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "85.62%",
    cgpa: "8.61",
  },
  {
    rollNo: "5231421110",
    name: "AMBALA DILEEP KUMAR",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "E.M-III, PDC, S&S, AEC LAB, DDV LAB, SSS LAB",
    attendancePercentage: "43.14%",
    cgpa: "0",
  },
  {
    rollNo: "5231421111",
    name: "ANDHAVARAPU MAHESWARA RAO",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "E.M-III, PDC, S&S, PE&UHV, AEC LAB, SSS LAB",
    attendancePercentage: "43.87%",
    cgpa: "0",
  },
  {
    rollNo: "5231421112",
    name: "ANISETTI RAM LAKSHMAN VINAY",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "63.23%",
    cgpa: "8.53",
  },
  {
    rollNo: "5231421113",
    name: "BONI SRINIVASA RAO",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "54.84%",
    cgpa: "0",
  },
  {
    rollNo: "5231421114",
    name: "BONTHU ANURADHA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "66.45%",
    cgpa: "6.91",
  },
  {
    rollNo: "5231421115",
    name: "BOTTA LOHITH MANIKANTA REDDY",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC, S&S",
    attendancePercentage: "63.23%",
    cgpa: "0",
  },
  {
    rollNo: "5231421116",
    name: "CHEKKA SRINIVASA RAHUL",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "70.32%",
    cgpa: "7.16",
  },
  {
    rollNo: "5231421117",
    name: "DABBIRU SAISWARUP",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "E.M-III, PDC, AEC LAB, SSS LAB",
    attendancePercentage: "36.77%",
    cgpa: "0",
  },
  {
    rollNo: "5231421118",
    name: "DALLAVALASA KRISHNA KUMAR",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "63.87%",
    cgpa: "7.33",
  },
  {
    rollNo: "5231421119",
    name: "GORSA KUSUMA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "71.61%",
    cgpa: "7.98",
  },
  {
    rollNo: "5231421120",
    name: "GUDLA LOKESH REDDY",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "E.M-III",
    attendancePercentage: "47.74%",
    cgpa: "0",
  },
  {
    rollNo: "5231421121",
    name: "INAKOTI SHARAN KUMAR",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC",
    attendancePercentage: "45.16%",
    cgpa: "0",
  },
  {
    rollNo: "5231421122",
    name: "IRUVADA SANKARA RAO",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "E.M-III, PDC, S&S, SSS LAB",
    attendancePercentage: "40.00%",
    cgpa: "0",
  },
  {
    rollNo: "5231421123",
    name: "KANNURU DEVANAND",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "AEC, PDC, S&S, AEC LAB, SSS LAB",
    attendancePercentage: "50.32%",
    cgpa: "0",
  },
  {
    rollNo: "5231421124",
    name: "KASARAPU TEJA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "76.47%",
    cgpa: "8.26",
  },
  {
    rollNo: "5231421125",
    name: "KOLLI PRASAD",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "71.61%",
    cgpa: "6.35",
  },
  {
    rollNo: "5231421126",
    name: "KOMMU PARDHA SARADHI",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "78.71%",
    cgpa: "8.33",
  },
  {
    rollNo: "5231421127",
    name: "KOSANA JAIKAR REDDY",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "76.13%",
    cgpa: "8.47",
  },
  {
    rollNo: "5231421128",
    name: "KUPPILI VENKATA SAI SASANK",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "71.61%",
    cgpa: "9.07",
  },
  {
    rollNo: "5231421129",
    name: "MADABATHULA YASHASWINI",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "84.52%",
    cgpa: "8.33",
  },
  {
    rollNo: "5231421130",
    name: "MALLENA RUPESH",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "PDC, AEC LAB",
    attendancePercentage: "45.16%",
    cgpa: "0",
  },
  {
    rollNo: "5231421131",
    name: "MENDA GAYATRI",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "92.90%",
    cgpa: "8.93",
  },
  {
    rollNo: "5231421132",
    name: "MURAPAKA RAJU",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "54.84%",
    cgpa: "6.07",
  },
  {
    rollNo: "5231421133",
    name: "MUTCHAKARLA ABHIRAM",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "E.M-III, PDC, S&S, AEC LAB, SSS LAB",
    attendancePercentage: "45.81%",
    cgpa: "0",
  },
  {
    rollNo: "5231421134",
    name: "MUVVALA HEMACHAND SRIVATHSAV",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "52.90%",
    cgpa: "6.7",
  },
  {
    rollNo: "5231421135",
    name: "PANDA DEVI SRI",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "50.32%",
    cgpa: "6.49",
  },
  {
    rollNo: "5231421136",
    name: "PILLALA KARUNYA SRINIVAS KUSHAAL",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "49.03%",
    cgpa: "6.07",
  },
  {
    rollNo: "5231421144",
    name: "VENKUMAHANTI RAJA MONIKA",
    year: "3rd",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "78.06%",
    cgpa: "8.53",
  },
  {
    rollNo: "5241421001",
    name: "Aalla Sreehitha",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.68",
  },
  {
    rollNo: "5241421002",
    name: "Adari Lokesh",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.59",
  },
  {
    rollNo: "5241421003",
    name: "Addala Naga Venkata Pavan",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.52",
  },
  {
    rollNo: "5241421004",
    name: "Akula Sai Charan",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "Maths-II",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421005",
    name: "Alajangi Gnanadeep",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.05",
  },
  {
    rollNo: "5241421006",
    name: "Alla Sai Ram",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "Eng, Maths-II, Phy, Chem, BEE, CP",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421007",
    name: "Allu Rohith",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "Maths-II, Phy, Chem, BEE",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421008",
    name: "Amballa Naga Venkata Manikanta",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.84",
  },
  {
    rollNo: "5241421009",
    name: "Anche Pavan Kumar",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "Maths-II, Phy, BEE",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421010",
    name: "Anche Ramya",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.66",
  },
  {
    rollNo: "5241421011",
    name: "Arava Mounika",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.52",
  },
  {
    rollNo: "5241421012",
    name: "Arle Pragna Sree",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.32",
  },
  {
    rollNo: "5241421013",
    name: "Avvari Yasaswini",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.48",
  },
  {
    rollNo: "5241421014",
    name: "Balaga Yaswanth",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.41",
  },
  {
    rollNo: "5241421015",
    name: "Bammidi Hemanth",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "Eng, Maths-II, Phy, Chem, BEE, CP",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421016",
    name: "Bandi Lokesh",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "Maths-II, Phy, Chem, BEE",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421017",
    name: "Bayana Vamshi",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.43",
  },
  {
    rollNo: "5241421018",
    name: "Chelluri Joshna Sree",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "Eng, Maths-II, Phy, Chem, BEE, CP",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421019",
    name: "Chilaka Poojitha",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.14",
  },
  {
    rollNo: "5241421020",
    name: "Chintada Koushik",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.66",
  },
  {
    rollNo: "5241421021",
    name: "Chitturi Sai Sri Ram",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "Maths-II",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421022",
    name: "Dabbiru Thanvi",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.52",
  },
  {
    rollNo: "5241421023",
    name: "Dadi Sriram",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "Maths-II, Phy, Chem, BEE, CP",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421024",
    name: "Duggi Hemanth Kumar Reddy",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.59",
  },
  {
    rollNo: "5241421025",
    name: "Gajulapalle Yaswanth Kumar Reddy",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.18",
  },
  {
    rollNo: "5241421026",
    name: "Gara Naga Venkata Durga Prasad",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.43",
  },
  {
    rollNo: "5241421027",
    name: "Gedela Rishitha",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.52",
  },
  {
    rollNo: "5241421028",
    name: "Gollu Keerthana",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.70",
  },
  {
    rollNo: "5241421029",
    name: "Gorli Manisha",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.66",
  },
  {
    rollNo: "5241421030",
    name: "Gudla Sravani",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.52",
  },
];




export default students;