const students = [
{
    rollNo: "5221421001",
    name: "GODAVARTHY SRI RANGA PADMAVATHI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "MOOCS",
    attendancePercentage: "69.67%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421002",
    name: "DEKKATHA RESHMA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "61.48%",
    cgpa: "8.25",
  },
  {
    rollNo: "5221421003",
    name: "PULAPA DHANISHA NAGA SAI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "74.59%",
    cgpa: "7.98",
  },
  {
    rollNo: "5221421004",
    name: "GURUGUBELLI MANISHA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "84.43%",
    cgpa: "7.65",
  },
  {
    rollNo: "5221421005",
    name: "PUDI CHANDRIKA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "VLSI, ELEC62, ELEOP61",
    attendancePercentage: "58.20%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421006",
    name: "RACHAKONDA NAGA TEJASVI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "69.67%",
    cgpa: "8.40",
  },
  {
    rollNo: "5221421007",
    name: "AGRAHARAPU VIJAYANAND",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "VLSI",
    attendancePercentage: "72.95%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421008",
    name: "ANNAM PRABASH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP, MWE, VLSI, ELEC62, ELEOP61",
    attendancePercentage: "69.67%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421009",
    name: "ARASAVILLI KOUSALYA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "72.95%",
    cgpa: "8.98",
  },
  {
    rollNo: "5221421010",
    name: "ASHISH KUMAR SHA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "MOOCS",
    attendancePercentage: "48.36%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421011",
    name: "ATI VENKATA SUDHINDRA KUMAR",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "80.33%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421012",
    name: "BADIGANTI CHARMINI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "80.33%",
    cgpa: "8.34",
  },
  {
    rollNo: "5221421013",
    name: "BASAVA HARISH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP, ELEC62, ELEOP61, DSP LAB",
    attendancePercentage: "61.48%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421014",
    name: "BAVIRISETTI KUSUMALATHA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "64.75%",
    cgpa: "9.11",
  },
  {
    rollNo: "5221421015",
    name: "BEHARA JAYARAM",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP LAB",
    attendancePercentage: "73.77%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421016",
    name: "BENDALAM SUPRIYA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "65.57%",
    cgpa: "9.22",
  },
  {
    rollNo: "5221421017",
    name: "BOGAVILLI KRISH KANJ",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP LAB",
    attendancePercentage: "60.66%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421018",
    name: "BOLLI HARI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "60.66%",
    cgpa: "7.14",
  },
  {
    rollNo: "5221421019",
    name: "BUDDHA PRANEETH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "ELEC62",
    attendancePercentage: "77.05%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421020",
    name: "CHANDAKA HEMACHANDRUNAIDU",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "ELEC62",
    attendancePercentage: "66.39%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421021",
    name: "CHENAGala MOHIT YADAV",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "ELEC62, ELEOP61",
    attendancePercentage: "60.66%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421022",
    name: "CHIGILIPALLI DHILLESWARA RAO",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP LAB",
    attendancePercentage: "97.54%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421023",
    name: "CHIKKALA PURNA SATHVIK",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "ELEC62, ELEOP61",
    attendancePercentage: "83.61%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421024",
    name: "DAMMU SAI UMA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "86.89%",
    cgpa: "8.02",
  },
  {
    rollNo: "5221421025",
    name: "DAMMU SURYA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "68.85%",
    cgpa: "6.56",
  },
  {
    rollNo: "5221421026",
    name: "DODDA SIVA MANI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "77.87%",
    cgpa: "7.19",
  },
  {
    rollNo: "5221421028",
    name: "DUPPALA SRIPURVA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "81.15%",
    cgpa: "8.83",
  },
  {
    rollNo: "5221421029",
    name: "GALI AKSHAY",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "78.69%",
    cgpa: "7.41",
  },
  {
    rollNo: "5221421031",
    name: "GUNDA GOWRESWARI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "82.79%",
    cgpa: "7.90",
  },
  {
    rollNo: "5221421032",
    name: "GUNTLA RAMYA SRI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "ELEOP61",
    attendancePercentage: "41.80%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421033",
    name: "GURI KOWSHIK",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "93.44%",
    cgpa: "8.03",
  },
  {
    rollNo: "5221421034",
    name: "HARSHITH MOULI MUTHY",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "72.95%",
    cgpa: "8.17",
  },
  {
    rollNo: "5221421035",
    name: "HYNDHAVIS S PRASANNA VINNAKOTA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "76.23%",
    cgpa: "9.06",
  },
  {
    rollNo: "5221421036",
    name: "IMIDISETTY SURESH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "68.03%",
    cgpa: "8.13",
  },
  {
    rollNo: "5221421037",
    name: "J VENKATA SURYA VEERA CHINMAYA ALOK NADH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "66.39%",
    cgpa: "6.90",
  },
  {
    rollNo: "5221421038",
    name: "JALDU HARSHITHA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "83.61%",
    cgpa: "8.55",
  },
  {
    rollNo: "5221421039",
    name: "KADUPU KUMARA ΜΑΝΙΚΑΝΤA UMA MAHESH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "81.97%",
    cgpa: "6.99",
  },
  {
    rollNo: "5221421040",
    name: "KASIMKOTA HARSHITHA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "64.75%",
    cgpa: "7.36",
  },
  {
    rollNo: "5221421041",
    name: "KILARI GOPINATH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "68.85%",
    cgpa: "7.21",
  },
  {
    rollNo: "5221421042",
    name: "KINJANGI BILVA GOPAL",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "64.75%",
    cgpa: "7.21",
  },
  {
    rollNo: "5221421043",
    name: "KOLLI PURUSHOTHAM REDDY",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "47.54%",
    cgpa: "6.90",
  },
  {
    rollNo: "5221421044",
    name: "KOMMU SARATH KUMAR",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "70.49%",
    cgpa: "6.57",
  },
  {
    rollNo: "5221421045",
    name: "KONDA PAVANI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "100.00%",
    cgpa: "8.81",
  },
  {
    rollNo: "5221421046",
    name: "KOPPUROTHU TARUN VIKRAM",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "48.36%",
    cgpa: "7.08",
  },
  {
    rollNo: "5221421047",
    name: "KORADA THANAY",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "74.59%",
    cgpa: "7.30",
  },
  {
    rollNo: "5221421048",
    name: "KORRAYI GOUTHAM",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "68.03%",
    cgpa: "7.86",
  },
  {
    rollNo: "5221421050",
    name: "LANKALAPALLI BHUVAN SAI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "70.49%",
    cgpa: "6.61",
  },
  {
    rollNo: "5221421051",
    name: "LENKA KUSUMA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "86.89%",
    cgpa: "8.47",
  },
  {
    rollNo: "5221421052",
    name: "LOKAREDDY SAI SURYA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "50.00%",
    cgpa: "7.06",
  },
  {
    rollNo: "5221421053",
    name: "MADHU SUDHAN YADAV",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP",
    attendancePercentage: "71.31%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421054",
    name: "МАЈЛ ЈАHANAVI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "57.38%",
    cgpa: "7.28",
  },
  {
    rollNo: "5221421055",
    name: "MALLA DHARMA TEJA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "81.97%",
    cgpa: "7.04",
  },
  {
    rollNo: "5221421056",
    name: "MAMIDI SANKET",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "48.36%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421057",
    name: "MANCHIKALAPUDI PRASANTH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP, MWE, VLSI, ELEOP61, DSP LAB",
    attendancePercentage: "75.41%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421058",
    name: "MANTHRI POOJITHA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "65.57%",
    cgpa: "8.72",
  },
  {
    rollNo: "5221421059",
    name: "MATTA SRINU",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "66.39%",
    cgpa: "6.69",
  },
  {
    rollNo: "5221421060",
    name: "MEESALA SAI RAMESH",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "MWE",
    attendancePercentage: "52.46%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421061",
    name: "MOHAMMAD AMEENA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "72.13%",
    cgpa: "8.02",
  },
  {
    rollNo: "5221421062",
    name: "N NANDA KALYANI",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "80.33%",
    cgpa: "7.68",
  },
  {
    rollNo: "5221421063",
    name: "NAGOTHI SANYASIRAO",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "74.59%",
    cgpa: "6.89",
  },
  {
    rollNo: "5221421064",
    name: "ΝΑΚΚΑ ΜΑΝΙΚΑΝΤΑ",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "51.64%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421136",
    name: "SABBISETTY HEMANTH KUMAR",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "ELEOP61, MOOCS",
    attendancePercentage: "45.08%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421137",
    name: "SRIPARNA SARKAR",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "60.66%",
    cgpa: "7.59",
  },
  {
    rollNo: "5221421138",
    name: "SUVVADA PREETHAM",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP, ELEC62",
    attendancePercentage: "40.98%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421139",
    name: "TAKKELLAPATI SAI ADITYA TEJA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "81.97%",
    cgpa: "7.19",
  },
  {
    rollNo: "5221421140",
    name: "TATAKULA SRI DATTA ΜΑΝΙΚΑΝTA SRIJAN",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "72.95%",
    cgpa: "8.90",
  },
  {
    rollNo: "5221421141",
    name: "TEKETI HARSHA VARDHAN",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "VLSI, ELEOP61, MOOCS",
    attendancePercentage: "49.18%",
    cgpa: "0.00",
  },
  {
    rollNo: "5221421142",
    name: "TERUKUTI TULASI RAM",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "None",
    attendancePercentage: "83.61%",
    cgpa: "6.91",
  },
  {
    rollNo: "5221421143",
    name: "VANDRANGI SUPRIYA",
    year: "4th",
    stream: "ECE B.Tech",
    backlogs: "DSP, DSP LAB, MIC EN LAB, PCS",
    attendancePercentage: "9.84%",
    cgpa: "0.00",
  },
  {
    rollNo: "5231421001",
    name: "ADDANKI NAGA SRAVANI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.61",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421002",
    name: "AKETI NIKHIL",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "7.79",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421003",
    name: "AKULA SAI LOKESH",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "7.76",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421004",
    name: "ALLU HARSHITHA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.57",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421005",
    name: "AMBATI MANIKANTA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS, DF",
    cgpa: "0.00",
    attendancePercentage: "84.00%",
  },
  {
    rollNo: "5231421006",
    name: "ARADHI SUPRIYA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.02",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421007",
    name: "ARI LAKSHMI PRASANNA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.39",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421008",
    name: "ARIKATLA CHANDRA SEKHAR",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS, DF",
    cgpa: "0.00",
    attendancePercentage: "84.00%",
  },
  {
    rollNo: "5231421009",
    name: "BADDI RAJESH",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS, DF",
    cgpa: "0.00",
    attendancePercentage: "88.00%",
  },
  {
    rollNo: "5231421010",
    name: "BAGADI JAYA SREE",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.48",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421011",
    name: "BALA SANYASI NAIDU",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421012",
    name: "BANDARU DILEEP KUMAR",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.14",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421013",
    name: "BARatam Kamala",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.86",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421014",
    name: "BEHARA SRI RAM",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "EMTL, AC, STLD",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421015",
    name: "BHAVANASI HEMANTH KUMAR",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421016",
    name: "BHIMAVARAPU HARSHINI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.32",
    attendancePercentage: "92.00%",
  },
  {
    rollNo: "5231421017",
    name: "BODDETI CHAKRADHAR",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.66",
    attendancePercentage: "92.00%",
  },
  {
    rollNo: "5231421018",
    name: "BONDA VENKATA KRISHNA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.63",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421019",
    name: "BUKYA LOKESH",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS, DF",
    cgpa: "0.00",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421020",
    name: "BURRA LAKSHMI PRASAD",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421021",
    name: "CHAPPIDI ANIL",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS, DF",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421022",
    name: "CHEKKA SAI BHARGAV",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421023",
    name: "CHINTA VAMSI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "AC",
    cgpa: "0.00",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421024",
    name: "CHODAVARAPU TEJASWINI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.48",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421025",
    name: "DADISETTI LOKESH",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "EMTL, AC, STLD, SS, DF",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421026",
    name: "DASARI NIKHIL KUMAR",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "7.74",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421027",
    name: "DATTA SAI VARDHAN",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421028",
    name: "DHAVALA VENKATA SAI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421029",
    name: "DOKALA SRI CHARAN",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421030",
    name: "DONDAPATI ESWAR",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421031",
    name: "DONGA RISHITHA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.34",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421032",
    name: "ESLAVATHU THARUN",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS, DF",
    cgpa: "0.00",
    attendancePercentage: "92.00%",
  },
  {
    rollNo: "5231421033",
    name: "GADUTHURI SAI BHARGAV",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "EMTL, AC",
    cgpa: "0.00",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421034",
    name: "GANTA SAI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "7.93",
    attendancePercentage: "92.00%",
  },
  {
    rollNo: "5231421035",
    name: "GEDELA SAI RAM",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS, DF",
    cgpa: "0.00",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421036",
    name: "GOKEDA SAI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "EMTL",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421061",
    name: "KURMAPU HEMA SUNDHAR",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.34",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421062",
    name: "MAHARANA GAYATHRI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.86",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421063",
    name: "MANDALA MOUNICA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.24",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421064",
    name: "MEDICHARLA SRIJA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.14",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421065",
    name: "MEESALA NAVEEN",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "STLD",
    cgpa: "0.00",
    attendancePercentage: "92.00%",
  },
  {
    rollNo: "5231421066",
    name: "MOHAMMADNOWMAN",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "AC, STLD",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421067",
    name: "MUDIDANA ROHITH",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421068",
    name: "MUNAGAVALASA GURU",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421069",
    name: "MUPPIDI SAI CHARAN",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "7.76",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421070",
    name: "NADIMPALLI BHARGAV",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.34",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421071",
    name: "NAGIREDDI ROHITH",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.39",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421072",
    name: "NAKKA DURGA PRASAD",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS, DF",
    cgpa: "0.00",
    attendancePercentage: "92.00%",
  },
  {
    rollNo: "5231421073",
    name: "NEELAM DINESH",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "AC",
    cgpa: "0.00",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421074",
    name: "PAGADALA ANIL",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.17",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421075",
    name: "PALAKA NIKHIL",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "7.41",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421076",
    name: "PANASA MOHAN",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421077",
    name: "PANDI MANIKANTA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.37",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421078",
    name: "PANTHAM LOKESH",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.28",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421079",
    name: "PARISE ANIL KUMAR",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421080",
    name: "PEDAPUDI AKHIL",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421081",
    name: "PEDDAKOTLA MANI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS, DF",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421082",
    name: "PENUGONDA GAYATHRI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.07",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421083",
    name: "PILLI JOSHNA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.72",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421084",
    name: "PINNINTI CHANDRA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.55",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421085",
    name: "PITHANI PRABHAS",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421086",
    name: "POLAKI LEELA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.93",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421087",
    name: "POTNURU GAYATHRI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.76",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421088",
    name: "PUDI OM SAI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421089",
    name: "PUJARI SAI KUMAR",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "P&S, EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421090",
    name: "PUVVULA MANIKUMAR",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "EMTL, AC, STLD, SS",
    cgpa: "0.00",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421091",
    name: "SABBAVARAPU VAMSI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "7.72",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421092",
    name: "SAKINALA SATHWIK",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.63",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421093",
    name: "SAMBANA HEMANTH",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.32",
    attendancePercentage: "96.00%",
  },
  {
    rollNo: "5231421094",
    name: "SANABOYINA MOUNIKA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "7.79",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421095",
    name: "SANAPATHI SAI",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.21",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5231421096",
    name: "SARAGADAM NAGA",
    year: "2nd",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.45",
    attendancePercentage: "100.00%",
  },
  {
    rollNo: "5241421001",
    name: "Aalla Sreehitha",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.68",
  },
  {
    rollNo: "5241421002",
    name: "Adari Lokesh",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.59",
  },
  {
    rollNo: "5241421003",
    name: "Addala Naga Venkata Pavan",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.52",
  },
  {
    rollNo: "5241421004",
    name: "Akula Sai Charan",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "Maths-II",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421005",
    name: "Alajangi Gnanadeep",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.05",
  },
  {
    rollNo: "5241421006",
    name: "Alla Sai Ram",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "Eng, Maths-II, Phy, Chem, BEE, CP",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421007",
    name: "Allu Rohith",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "Maths-II, Phy, Chem, BEE",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421008",
    name: "Amballa Naga Venkata Manikanta",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "8.84",
  },
  {
    rollNo: "5241421009",
    name: "Anche Pavan Kumar",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "Maths-II, Phy, BEE",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421010",
    name: "Anche Ramya",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.66",
  },
  {
    rollNo: "5241421011",
    name: "Arava Mounika",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.52",
  },
  {
    rollNo: "5241421012",
    name: "Arle Pragna Sree",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.32",
  },
  {
    rollNo: "5241421013",
    name: "Avvari Yasaswini",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.48",
  },
  {
    rollNo: "5241421014",
    name: "Balaga Yaswanth",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.41",
  },
  {
    rollNo: "5241421015",
    name: "Bammidi Hemanth",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "Eng, Maths-II, Phy, Chem, BEE, CP",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421016",
    name: "Bandi Lokesh",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "Maths-II, Phy, Chem, BEE",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421017",
    name: "Bayana Vamshi",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.43",
  },
  {
    rollNo: "5241421018",
    name: "Chelluri Joshna Sree",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "Eng, Maths-II, Phy, Chem, BEE, CP",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421019",
    name: "Chilaka Poojitha",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.14",
  },
  {
    rollNo: "5241421020",
    name: "Chintada Koushik",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.66",
  },
  {
    rollNo: "5241421021",
    name: "Chitturi Sai Sri Ram",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "Maths-II",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421022",
    name: "Dabbiru Thanvi",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.52",
  },
  {
    rollNo: "5241421023",
    name: "Dadi Sriram",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "Maths-II, Phy, Chem, BEE, CP",
    cgpa: "0.00",
  },
  {
    rollNo: "5241421024",
    name: "Duggi Hemanth Kumar Reddy",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.59",
  },
  {
    rollNo: "5241421025",
    name: "Gajulapalle Yaswanth Kumar Reddy",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.18",
  },
  {
    rollNo: "5241421026",
    name: "Gara Naga Venkata Durga Prasad",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.43",
  },
  {
    rollNo: "5241421027",
    name: "Gedela Rishitha",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.52",
  },
  {
    rollNo: "5241421028",
    name: "Gollu Keerthana",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.70",
  },
  {
    rollNo: "5241421029",
    name: "Gorli Manisha",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.66",
  },
  {
    rollNo: "5241421030",
    name: "Gudla Sravani",
    year: "1st",
    stream: "ECE B.Tech",
    backlogs: "None",
    cgpa: "9.52",
  },
];




export default students;