const teachers = [
  {
    name: "Dr. S. Krishna Veni",
    designation: "Professor",
    department: "Electronics and Communication Engineering",
    qualification: "M.Tech, Ph. D",
    specialization: "Antenna Arrays",
    email: "drkrishnaveni@gvpcdpgc.edu.in",
  },
  {
    name: "Dr. P. A. Nageswara Rao",
    designation: "Professor & H.O.D",
    department: "Electronics and Communication Engineering",
    qualification: "M.E, Ph. D",
    specialization: "Process Controlled Instrumentation, Antenna",
    email: "drnageswararao@gvpcdpgc.edu.in",
  },
  {
    name: "Dr. V.Adinarayana",
    designation: "Associate Professor",
    department: "Electronics and Communication Engineering",
    qualification: "B.E, M.E, Ph.D",
    specialization: "Wireless Communications",
    email: "dradinarayana@gvpcdpgc.edu.in",
  },
  {
    name: "Dr. Ch. Manohar Kumar",
    designation: "Associate Professor",
    department: "Electronics and Communication Engineering",
    qualification: "B. Tech, M. Tech, PG(AI-IITK), Ph.D",
    specialization: "Radar & Microwave Engineering",
    email: "manohar@gvpcdpgc.edu.in",
  },
  {
    name: "Mr. S. Venkatesh",
    designation: "Assistant Professor",
    department: "Electronics and Communication Engineering",
    qualification: "B. Tech, M. Tech",
    specialization: "V.L.S.I System Design",
    email: "venkateshece@gvpcdpgc.edu.in",
  },
  {
    name: "Mr. V. Ram Nishanth",
    designation: "Assistant Professor",
    department: "Electronics and Communication Engineering",
    qualification: "B. Tech, M. Tech",
    specialization: "Communication Systems",
    email: "ramnishanthvanka@gvpcdpgc.edu.in",
  },
  {
    name: "Mr. A. Mahesh Babu",
    designation: "Assistant Professor",
    department: "Electronics and Communication Engineering",
    qualification: "B.Tech, M.Tech",
    specialization: "Radar & Microwave Engineering",
    email: "maheshbabu07402@gvpcdpgc.edu.in",
  },
  {
    name: "Mrs. G.Sowjanya Lakshmi",
    designation: "Assistant Professor",
    department: "Electronics and Communication Engineering",
    qualification: "B.E, M.Tech",
    specialization: "V.L.S.I System Design",
    email: "G.Sowjanya@gvpcdpgc.edu.in",
  },
  {
    name: "Mrs. P.N.S Sailaja",
    designation: "Assistant Professor",
    department: "Electronics and Communication Engineering",
    qualification: "M.Tech",
    specialization: "Digital Image Processing",
    email: "Mrs.P.N.S Sailaja@gvpcdpgc.edu.in",
  },
  {
    name: "Mrs. Aruna. Adlaboina",
    designation: "Assistant Professor",
    department: "Electronics and Communication Engineering",
    qualification: "B.Tech, M.Tech",
    specialization: "Systems and Signal Processing",
    email: "arunaece@gvpcdpgc.edu.in",
  },
  {
    name: "Mrs. K. Deepthi",
    designation: "Assistant Professor",
    department: "Electronics and Communication Engineering",
    qualification: "B.Tech, M.Tech",
    specialization: "VLSI",
    email: "deepthi@gvpcdpgc.edu.in",
  },
  {
    name: "Mr. E. Raju",
    designation: "Assistant Professor",
    department: "Electronics and Communication Engineering",
    qualification: "B.Tech, M.Tech",
    specialization: "Digital Systems and Signal Processing",
    email: "rajuegala@gvpcdpgc.edu.in",
  },
  {
    name: "Mrs. M. Tharangini",
    designation: "Assistant Professor",
    department: "Electronics and Communication Engineering",
    qualification: "B.Tech, M.Tech",
    specialization: "Embedded Systems",
    email: "mtharangini@gvpcdpgc.edu.in",
  },
  {
    name: "Mrs. V. Sridevi",
    designation: "Assistant Professor",
    department: "Electronics and Communication Engineering",
    qualification: "B.Tech, M.Tech",
    specialization: "Communication Systems",
    email: "sridevivelaga@gvpcdpgc.edu.in",
  },
  {
    name: "Mr. Ch. Krishna Chaitanya Sai",
    designation: "Assistant Professor",
    department: "Electronics and Communication Engineering",
    qualification: "B.Tech, M.Tech",
    specialization: "VLSI",
    email: "krishnachaitanyach4@gvpcdpgc.edu.in",
  },
];


export default teachers;